import type { AircraftDefinition } from './types';

export const aircraftDatabase: AircraftDefinition[] = [
  // ─────────────────────────────────────────────────
  // PISTON SINGLES
  // ─────────────────────────────────────────────────
  {
    make: 'Cessna',
    model: '172 Skyhawk',
    variant: '172S',
    yearStart: 1956,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(1) Lycoming IO-360-L2A, 180 hp',
    maxFuelGal: 56,
    cruiseSpeedKts: 124,
    typicalBurnGph: 8.5,
    burnRangeGph: [7.0, 11.0],
    maxRampWeightLbs: 2558,
    maxZeroFuelWeightLbs: 2200,
    basicOperatingWeightLbs: 1680,
    maxPayloadLbs: 520,
    reservesTypicalGal: 6.4,
    reservesNbaaGal: 4.3,
    burnPenaltyPerHrPct: 2.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna 172S POH, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn rate based on 75% power cruise at 8,000 ft. Lean of peak operations can reduce burn to ~7.5 gph. | 56 gal total fuel with 53 gal usable. | Piston aircraft burn penalty is minimal — 2% accounts for mixture enrichment at lower altitudes and leaning discipline. | The 172S is the most-produced aircraft in history; real-world burn varies widely with operator technique.',
  },
  {
    make: 'Cessna',
    model: '182 Skylane',
    variant: '182T',
    yearStart: 1956,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(1) Lycoming IO-540-AB1A5, 230 hp',
    maxFuelGal: 87,
    cruiseSpeedKts: 145,
    typicalBurnGph: 13.0,
    burnRangeGph: [10.5, 15.5],
    maxRampWeightLbs: 3100,
    maxZeroFuelWeightLbs: 2700,
    basicOperatingWeightLbs: 1970,
    maxPayloadLbs: 730,
    reservesTypicalGal: 9.8,
    reservesNbaaGal: 6.5,
    burnPenaltyPerHrPct: 2.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna 182T POH, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn rate at 75% power cruise, ~10,000 ft. Lean of peak can reduce to ~11 gph. | 87 gal total (80 gal usable standard tanks). | Higher useful load than 172 makes it a better platform for fuel tankering on short trips.',
  },
  {
    make: 'Piper',
    model: 'PA-28 Cherokee/Archer',
    variant: 'PA-28-181 Archer III',
    yearStart: 1961,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(1) Lycoming O-360-A4M, 180 hp',
    maxFuelGal: 50,
    cruiseSpeedKts: 128,
    typicalBurnGph: 10.0,
    burnRangeGph: [8.0, 12.0],
    maxRampWeightLbs: 2558,
    maxZeroFuelWeightLbs: 2200,
    basicOperatingWeightLbs: 1625,
    maxPayloadLbs: 575,
    reservesTypicalGal: 7.5,
    reservesNbaaGal: 5.0,
    burnPenaltyPerHrPct: 2.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Piper PA-28-181 Archer III POH, Piper Aircraft',
    dataSourceDate: '2020',
    operatorNotes: 'Burn rate at 75% power, ~6,000 ft. 50 gal total with 48 gal usable. | The Cherokee family has many variants — verify your specific model POH. | Carbureted O-360 engine; mixture management affects burn significantly.',
  },
  {
    make: 'Cirrus',
    model: 'SR22',
    variant: 'SR22 G6',
    yearStart: 2001,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(1) Continental IO-550-N, 310 hp',
    maxFuelGal: 81,
    cruiseSpeedKts: 186,
    typicalBurnGph: 17.7,
    burnRangeGph: [14.0, 20.0],
    maxRampWeightLbs: 3400,
    maxZeroFuelWeightLbs: 2900,
    basicOperatingWeightLbs: 2280,
    maxPayloadLbs: 620,
    reservesTypicalGal: 13.3,
    reservesNbaaGal: 8.9,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cirrus SR22 G6 POH, Cirrus Aircraft',
    dataSourceDate: '2023',
    operatorNotes: 'Burn rate at 75% power, 8,000 ft, best power mixture. Lean of peak operation reduces burn to ~14.5 gph at cost of ~8 kts. | 81 gal total (78 gal usable). | CAPS parachute system adds ~60 lbs to empty weight. | G1–G7 variants have slightly different weights and avionics; verify your specific generation.',
  },
  {
    make: 'Cirrus',
    model: 'SR22T',
    variant: 'SR22T G6',
    yearStart: 2010,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(1) Continental TSIO-550-K, 315 hp (turbonormalized)',
    maxFuelGal: 81,
    cruiseSpeedKts: 214,
    typicalBurnGph: 18.5,
    burnRangeGph: [15.0, 22.0],
    maxRampWeightLbs: 3600,
    maxZeroFuelWeightLbs: 3050,
    basicOperatingWeightLbs: 2370,
    maxPayloadLbs: 680,
    reservesTypicalGal: 13.9,
    reservesNbaaGal: 9.3,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cirrus SR22T G6 POH, Cirrus Aircraft',
    dataSourceDate: '2023',
    operatorNotes: 'Turbonormalized variant maintains sea-level power to FL250. Burn rate at 85% power, FL180. | Lean of peak reduces burn to ~15.5 gph. | Higher gross weight than naturally aspirated SR22. | Real-world operators commonly flight plan 18–19 gph at high altitude cruise.',
  },
  {
    make: 'Beechcraft',
    model: 'Bonanza A36',
    variant: 'A36',
    yearStart: 1968,
    yearEnd: 2005,
    fuelType: 'AvGas',
    engines: '(1) Continental IO-550-B, 300 hp',
    maxFuelGal: 74,
    cruiseSpeedKts: 176,
    typicalBurnGph: 14.4,
    burnRangeGph: [11.5, 17.0],
    maxRampWeightLbs: 3650,
    maxZeroFuelWeightLbs: 3100,
    basicOperatingWeightLbs: 2385,
    maxPayloadLbs: 715,
    reservesTypicalGal: 10.8,
    reservesNbaaGal: 7.2,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Beechcraft Bonanza A36 POH, Beech Aircraft Corporation',
    dataSourceDate: '2004',
    operatorNotes: 'Burn rate at 75% power, 8,000 ft. Lean of peak reduces burn to ~12 gph. | 74 gal total (44 gal standard, 74 gal with long range tanks). | The A36 is the long-body straight-tail Bonanza; earlier V-tail models have different performance. | Production ended 2005 but large fleet still active.',
  },
  {
    make: 'Mooney',
    model: 'M20J/M20TN',
    variant: 'M20J 201',
    yearStart: 1977,
    yearEnd: 1998,
    fuelType: 'AvGas',
    engines: '(1) Lycoming IO-360-A3B6D, 200 hp',
    maxFuelGal: 64,
    cruiseSpeedKts: 155,
    typicalBurnGph: 9.5,
    burnRangeGph: [8.0, 11.5],
    maxRampWeightLbs: 2740,
    maxZeroFuelWeightLbs: 2350,
    basicOperatingWeightLbs: 1800,
    maxPayloadLbs: 550,
    reservesTypicalGal: 7.1,
    reservesNbaaGal: 4.8,
    burnPenaltyPerHrPct: 2.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Mooney M20J POH, Mooney Aircraft Corporation',
    dataSourceDate: '1995',
    operatorNotes: 'The M20J "201" is known for its exceptional fuel efficiency — 155 kts on 9.5 gph is among the best in class. | 64 gal total (52 gal usable standard, 64 gal with long range tanks). | Mooney ceased production in 2019; parts availability is a consideration. | M20TN Acclaim has turbonormalized TSIO-360 with higher burn rates (~13 gph) and faster cruise (~195 kts).',
  },

  // ─────────────────────────────────────────────────
  // PISTON TWINS
  // ─────────────────────────────────────────────────
  {
    make: 'Cessna',
    model: '310',
    variant: '310R',
    yearStart: 1954,
    yearEnd: 1980,
    fuelType: 'AvGas',
    engines: '(2) Continental IO-520-M, 285 hp each',
    maxFuelGal: 100,
    cruiseSpeedKts: 195,
    typicalBurnGph: 26.0,
    burnRangeGph: [22.0, 32.0],
    maxRampWeightLbs: 5500,
    maxZeroFuelWeightLbs: 4700,
    basicOperatingWeightLbs: 3660,
    maxPayloadLbs: 1040,
    reservesTypicalGal: 19.5,
    reservesNbaaGal: 13.0,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna 310R POH, Cessna Aircraft Company',
    dataSourceDate: '1979',
    operatorNotes: 'Burn rate at 65% power, 8,000 ft with both engines. 100 gal usable (207 gal total with tip and aux tanks on later models). | Out of production since 1980 but substantial fleet remains. | Single-engine performance is marginal at max gross — factor this into route planning. | Fuel burn varies significantly between 310 variants (A through R).',
  },
  {
    make: 'Piper',
    model: 'PA-34 Seneca',
    variant: 'PA-34-220T Seneca V',
    yearStart: 1972,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(2) Continental TSIO-360-RB, 220 hp each (turbocharged)',
    maxFuelGal: 98,
    cruiseSpeedKts: 170,
    typicalBurnGph: 22.0,
    burnRangeGph: [18.0, 27.0],
    maxRampWeightLbs: 4750,
    maxZeroFuelWeightLbs: 4100,
    basicOperatingWeightLbs: 3263,
    maxPayloadLbs: 837,
    reservesTypicalGal: 16.5,
    reservesNbaaGal: 11.0,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Piper PA-34-220T Seneca V POH, Piper Aircraft',
    dataSourceDate: '2018',
    operatorNotes: 'Burn at 75% power, 10,000 ft. Turbocharged engines allow efficient cruise at higher altitudes. | 98 gal total (93 gal usable). | Popular multi-engine trainer and light charter aircraft. | Earlier Seneca I/II variants have naturally aspirated engines with different performance.',
  },
  {
    make: 'Beechcraft',
    model: 'Baron 58',
    variant: 'Baron 58',
    yearStart: 1970,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(2) Continental IO-550-C, 300 hp each',
    maxFuelGal: 166,
    cruiseSpeedKts: 200,
    typicalBurnGph: 28.0,
    burnRangeGph: [24.0, 34.0],
    maxRampWeightLbs: 5524,
    maxZeroFuelWeightLbs: 4800,
    basicOperatingWeightLbs: 3670,
    maxPayloadLbs: 1130,
    reservesTypicalGal: 21.0,
    reservesNbaaGal: 14.0,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Beechcraft Baron 58 POH, Textron Aviation',
    dataSourceDate: '2020',
    operatorNotes: 'Burn at 65% power, 8,000 ft. 166 gal total with aux tanks (100 gal standard). | Excellent single-engine performance for its class. | Still in production; one of the last piston twins manufactured. | Real-world operators report 26–30 gph in economy cruise.',
  },
  {
    make: 'Piper',
    model: 'PA-44 Seminole',
    variant: 'PA-44-180',
    yearStart: 1979,
    yearEnd: null,
    fuelType: 'AvGas',
    engines: '(2) Lycoming O-360-A1H6, 180 hp each',
    maxFuelGal: 108,
    cruiseSpeedKts: 162,
    typicalBurnGph: 16.0,
    burnRangeGph: [13.0, 20.0],
    maxRampWeightLbs: 3816,
    maxZeroFuelWeightLbs: 3300,
    basicOperatingWeightLbs: 2570,
    maxPayloadLbs: 730,
    reservesTypicalGal: 12.0,
    reservesNbaaGal: 8.0,
    burnPenaltyPerHrPct: 2.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Piper PA-44-180 Seminole POH, Piper Aircraft',
    dataSourceDate: '2019',
    operatorNotes: 'Burn at 75% power, 8,000 ft. 108 gal total (108 gal usable). | Counter-rotating props eliminate critical engine considerations. | Primarily used as a multi-engine trainer. | Fuel-efficient for a twin at 16 gph total (8 gph per engine).',
  },

  // ─────────────────────────────────────────────────
  // TURBOPROPS
  // ─────────────────────────────────────────────────
  {
    make: 'Beechcraft',
    model: 'King Air C90GTx',
    variant: 'C90GTx',
    yearStart: 2009,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PT6A-135A, 550 shp each',
    maxFuelGal: 384,
    cruiseSpeedKts: 226,
    typicalBurnGph: 72.0,
    burnRangeGph: [58.0, 90.0],
    maxRampWeightLbs: 10485,
    maxZeroFuelWeightLbs: 8500,
    basicOperatingWeightLbs: 6765,
    maxPayloadLbs: 1735,
    reservesTypicalGal: 54.0,
    reservesNbaaGal: 36.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Beechcraft King Air C90GTx Specification Sheet, Textron Aviation',
    dataSourceDate: '2022',
    operatorNotes: 'Burn rate at max cruise, FL260. Economy cruise at FL280 reduces burn to ~58 gph. | 384 gal (2,574 lbs Jet-A). | The King Air 90 series is the entry-level King Air; excellent short-field performance. | PT6A engines are known for reliability and ease of maintenance. | Real-world operators typically plan 70–80 gph.',
  },
  {
    make: 'Beechcraft',
    model: 'King Air B200GT',
    variant: 'B200GT',
    yearStart: 2008,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PT6A-52, 850 shp each',
    maxFuelGal: 544,
    cruiseSpeedKts: 289,
    typicalBurnGph: 100.0,
    burnRangeGph: [82.0, 125.0],
    maxRampWeightLbs: 12590,
    maxZeroFuelWeightLbs: 9800,
    basicOperatingWeightLbs: 8283,
    maxPayloadLbs: 1517,
    reservesTypicalGal: 75.0,
    reservesNbaaGal: 50.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Beechcraft King Air B200GT Specification Sheet, Textron Aviation',
    dataSourceDate: '2022',
    operatorNotes: 'Burn at high-speed cruise, FL270. Economy cruise (~270 kts) reduces burn to ~85 gph. | 544 gal (3,645 lbs Jet-A). | The B200GT has composite winglets and upgraded avionics over the standard B200. | Workhorse of the King Air line; large installed fleet worldwide.',
  },
  {
    make: 'Beechcraft',
    model: 'King Air 350i',
    variant: '350i',
    yearStart: 2009,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PT6A-60A, 1,050 shp each',
    maxFuelGal: 539,
    cruiseSpeedKts: 312,
    typicalBurnGph: 117.0,
    burnRangeGph: [95.0, 145.0],
    maxRampWeightLbs: 15100,
    maxZeroFuelWeightLbs: 11500,
    basicOperatingWeightLbs: 9580,
    maxPayloadLbs: 1920,
    reservesTypicalGal: 87.8,
    reservesNbaaGal: 58.5,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Beechcraft King Air 350i Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL350. The 350i is the largest and fastest King Air variant. | 539 gal (3,611 lbs Jet-A). | Cabin is stretched over the B200 with stand-up headroom. | Competes with light jets on speed while retaining turboprop short-field capability and lower operating costs.',
  },
  {
    make: 'Pilatus',
    model: 'PC-12 NGX',
    variant: 'PC-12/47E NGX',
    yearStart: 2020,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(1) Pratt & Whitney Canada PT6E-67XP, 1,845 shp',
    maxFuelGal: 402,
    cruiseSpeedKts: 285,
    typicalBurnGph: 66.0,
    burnRangeGph: [54.0, 82.0],
    maxRampWeightLbs: 10450,
    maxZeroFuelWeightLbs: 8500,
    basicOperatingWeightLbs: 6893,
    maxPayloadLbs: 1607,
    reservesTypicalGal: 49.5,
    reservesNbaaGal: 33.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Pilatus PC-12 NGX Specification Sheet, Pilatus Aircraft Ltd',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at max cruise, FL280. Economy cruise at FL300 reduces burn to ~55 gph. | 402 gal (2,693 lbs Jet-A). | Single-engine turboprop with excellent dispatch reliability. | The NGX features an autothrottle and FADEC-controlled engine. | Large cargo door makes it versatile for mixed passenger/cargo operations.',
  },
  {
    make: 'Daher',
    model: 'TBM 960',
    variant: 'TBM 960',
    yearStart: 2022,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(1) Pratt & Whitney Canada PT6E-66XT, 850 shp',
    maxFuelGal: 282,
    cruiseSpeedKts: 330,
    typicalBurnGph: 60.0,
    burnRangeGph: [48.0, 75.0],
    maxRampWeightLbs: 7394,
    maxZeroFuelWeightLbs: 5900,
    basicOperatingWeightLbs: 4695,
    maxPayloadLbs: 1205,
    reservesTypicalGal: 45.0,
    reservesNbaaGal: 30.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Daher TBM 960 Specification Sheet, Daher',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at max cruise, FL310. The TBM 960 is the fastest single-engine turboprop in production at 330 KTAS. | 282 gal (1,889 lbs Jet-A). | FADEC-controlled PT6E engine with autothrottle. | Real-world operators report 55–65 gph depending on altitude and ISA deviation. | Excellent owner-flown aircraft with Garmin G3000 avionics.',
  },
  {
    make: 'Piper',
    model: 'M600',
    variant: 'M600/SLS',
    yearStart: 2016,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(1) Pratt & Whitney Canada PT6A-42A, 600 shp',
    maxFuelGal: 260,
    cruiseSpeedKts: 274,
    typicalBurnGph: 50.0,
    burnRangeGph: [40.0, 62.0],
    maxRampWeightLbs: 6000,
    maxZeroFuelWeightLbs: 4910,
    basicOperatingWeightLbs: 3826,
    maxPayloadLbs: 1084,
    reservesTypicalGal: 37.5,
    reservesNbaaGal: 25.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Piper M600/SLS Specification Sheet, Piper Aircraft',
    dataSourceDate: '2022',
    operatorNotes: 'Burn at max cruise, FL280. Economy cruise reduces burn to ~42 gph. | 260 gal (1,742 lbs Jet-A). | The SLS variant includes Garmin Autoland (GFC 700 autopilot with Emergency Descent Mode and Autoland). | Pressurized cabin to FL300. | Competes with TBM and PC-12 at a lower price point.',
  },
  {
    make: 'Cessna',
    model: '208 Caravan',
    variant: '208B Grand Caravan EX',
    yearStart: 1984,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(1) Pratt & Whitney Canada PT6A-140, 867 shp',
    maxFuelGal: 332,
    cruiseSpeedKts: 186,
    typicalBurnGph: 55.0,
    burnRangeGph: [45.0, 68.0],
    maxRampWeightLbs: 8785,
    maxZeroFuelWeightLbs: 7200,
    basicOperatingWeightLbs: 5145,
    maxPayloadLbs: 2055,
    reservesTypicalGal: 41.3,
    reservesNbaaGal: 27.5,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna 208B Grand Caravan EX Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at max cruise, FL100. Unpressurized — typically operated at 10,000–12,000 ft. | 332 gal (2,224 lbs Jet-A). | Enormous cargo capacity; the workhorse of bush and cargo operations worldwide. | FedEx feeder operations are the largest fleet operator. | Excellent short-field and rough-field capability.',
  },
  {
    make: 'Daher',
    model: 'TBM 850',
    variant: 'TBM 850',
    yearStart: 2006,
    yearEnd: 2013,
    fuelType: 'JetA',
    engines: '(1) Pratt & Whitney Canada PT6A-66D, 850 shp',
    maxFuelGal: 282,
    cruiseSpeedKts: 320,
    typicalBurnGph: 58.0,
    burnRangeGph: [47.0, 72.0],
    maxRampWeightLbs: 7394,
    maxZeroFuelWeightLbs: 5900,
    basicOperatingWeightLbs: 4629,
    maxPayloadLbs: 1271,
    reservesTypicalGal: 43.5,
    reservesNbaaGal: 29.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Daher TBM 850 POH, SOCATA/Daher',
    dataSourceDate: '2012',
    operatorNotes: 'Burn at max cruise, FL310. Predecessor to the TBM 900/910/930/960 series. | 282 gal (1,889 lbs Jet-A). | Mechanically controlled PT6A-66D (no FADEC). | Slightly lower cruise speed than TBM 960 due to older prop and engine control. | Many TBM 850s have been upgraded with G1000NXi avionics.',
  },

  // ─────────────────────────────────────────────────
  // LIGHT JETS
  // ─────────────────────────────────────────────────
  {
    make: 'Cessna',
    model: 'Citation Mustang',
    variant: '510',
    yearStart: 2006,
    yearEnd: 2017,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW615F, 1,460 lb thrust each',
    maxFuelGal: 241,
    cruiseSpeedKts: 340,
    typicalBurnGph: 104.0,
    burnRangeGph: [88.0, 128.0],
    maxRampWeightLbs: 8730,
    maxZeroFuelWeightLbs: 6750,
    basicOperatingWeightLbs: 5660,
    maxPayloadLbs: 1090,
    reservesTypicalGal: 78.0,
    reservesNbaaGal: 52.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation Mustang Specification Sheet, Cessna Aircraft Company',
    dataSourceDate: '2016',
    operatorNotes: 'Burn at high-speed cruise, FL350. Long range cruise at FL410 reduces burn to ~88 gph. | 241 gal (1,615 lbs Jet-A). | Entry-level Citation; single-pilot certified. | Production ended 2017 but popular on pre-owned market. | No lavatory in standard configuration limits utility for longer trips.',
  },
  {
    make: 'Cessna',
    model: 'Citation M2 Gen2',
    variant: '525',
    yearStart: 2013,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-1AP-21, 1,965 lb thrust each',
    maxFuelGal: 302,
    cruiseSpeedKts: 404,
    typicalBurnGph: 115.0,
    burnRangeGph: [96.0, 140.0],
    maxRampWeightLbs: 10700,
    maxZeroFuelWeightLbs: 8200,
    basicOperatingWeightLbs: 6905,
    maxPayloadLbs: 1295,
    reservesTypicalGal: 86.3,
    reservesNbaaGal: 57.5,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation M2 Gen2 Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL390. Long range cruise reduces burn to ~98 gph. | 302 gal (2,023 lbs Jet-A). | Replaced the Citation CJ1+ and CitationJet. | Gen2 features Garmin G3000 touchscreen avionics. | Single-pilot certified; popular owner-flown light jet.',
  },
  {
    make: 'Cessna',
    model: 'Citation CJ2+',
    variant: '525A',
    yearStart: 2006,
    yearEnd: 2015,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-3A-24, 2,490 lb thrust each',
    maxFuelGal: 430,
    cruiseSpeedKts: 418,
    typicalBurnGph: 120.0,
    burnRangeGph: [100.0, 150.0],
    maxRampWeightLbs: 12500,
    maxZeroFuelWeightLbs: 9500,
    basicOperatingWeightLbs: 7884,
    maxPayloadLbs: 1616,
    reservesTypicalGal: 90.0,
    reservesNbaaGal: 60.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation CJ2+ Specification Sheet, Cessna Aircraft Company',
    dataSourceDate: '2014',
    operatorNotes: 'Burn at high-speed cruise, FL410. Long range cruise reduces burn to ~102 gph. | 430 gal (2,881 lbs Jet-A). | Single-pilot certified. | Replaced by the CJ3+ which shares similar performance but with updated avionics. | Well-regarded for range and cabin size in its class.',
  },
  {
    make: 'Cessna',
    model: 'Citation CJ3+',
    variant: '525B',
    yearStart: 2014,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-3A, 2,820 lb thrust each',
    maxFuelGal: 460,
    cruiseSpeedKts: 416,
    typicalBurnGph: 122.0,
    burnRangeGph: [102.0, 155.0],
    maxRampWeightLbs: 13870,
    maxZeroFuelWeightLbs: 10500,
    basicOperatingWeightLbs: 8530,
    maxPayloadLbs: 1970,
    reservesTypicalGal: 91.5,
    reservesNbaaGal: 61.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation CJ3+ Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL410. Long range cruise reduces burn to ~105 gph. | 460 gal (3,082 lbs Jet-A). | Garmin G3000 touchscreen avionics. | Single-pilot certified. | Popular step-up from CJ2+ with improved range and cabin comfort.',
  },
  {
    make: 'Cessna',
    model: 'Citation CJ4',
    variant: 'CJ4',
    yearStart: 2010,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-4A, 3,621 lb thrust each',
    maxFuelGal: 870,
    cruiseSpeedKts: 432,
    typicalBurnGph: 126,
    burnRangeGph: [115, 180],
    maxRampWeightLbs: 17230,
    maxZeroFuelWeightLbs: 12500,
    basicOperatingWeightLbs: 10350,
    maxPayloadLbs: 1052,
    reservesTypicalGal: 147,
    reservesNbaaGal: 136,
    burnPenaltyPerHrPct: 2.5,
    confidence: {
      weights: 'verified',
      fuelCapacity: 'verified',
      burnRate: 'verified',
      burnPenalty: 'verified',
      reserves: 'verified',
    },
    dataSource: 'Cessna Citation CJ4 Flight Planning Guide, Cessna Aircraft Company',
    dataSourceDate: 'September 2012',
    operatorNotes: 'Burn rate defaults to Long Range Cruise at FL410 (126 gph). For High Speed Cruise planning, use 177 gph. | Real-world operators typically report 130–160 gph depending on altitude, payload, and power setting. | Burn penalty of 2.5%/hr is derived from POH tables and is lower than typical jet defaults — the FJ44-4A engine is efficient at altitude. | Max fuel of 870 gal (5,828 lb) assumes 6.7 lb/gal Jet-A density at ISA standard conditions. | NBAA IFR reserves (136 gal) assume 100 nm alternate. Adjust for your actual alternate distance. | This aircraft entry is sourced from the official Flight Planning Guide. Always verify against your aircraft\'s current AFM.',
  },
  {
    make: 'Embraer',
    model: 'Phenom 100EV',
    variant: 'EMB-500 100EV',
    yearStart: 2017,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW617F1-E, 1,695 lb thrust each',
    maxFuelGal: 373,
    cruiseSpeedKts: 390,
    typicalBurnGph: 112.0,
    burnRangeGph: [92.0, 138.0],
    maxRampWeightLbs: 10582,
    maxZeroFuelWeightLbs: 8200,
    basicOperatingWeightLbs: 6945,
    maxPayloadLbs: 1255,
    reservesTypicalGal: 84.0,
    reservesNbaaGal: 56.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Embraer Phenom 100EV Specification Sheet, Embraer Executive Jets',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL370. Long range cruise reduces burn to ~94 gph. | 373 gal (2,499 lbs Jet-A). | Single-pilot certified. | EV variant features more powerful engines and increased range over original Phenom 100. | Excellent training platform for light jet operations.',
  },
  {
    make: 'Embraer',
    model: 'Phenom 300E',
    variant: 'EMB-505 300E',
    yearStart: 2020,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW535E1, 3,478 lb thrust each',
    maxFuelGal: 524,
    cruiseSpeedKts: 453,
    typicalBurnGph: 145.0,
    burnRangeGph: [120.0, 180.0],
    maxRampWeightLbs: 18387,
    maxZeroFuelWeightLbs: 13500,
    basicOperatingWeightLbs: 11622,
    maxPayloadLbs: 1878,
    reservesTypicalGal: 108.8,
    reservesNbaaGal: 72.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Embraer Phenom 300E Specification Sheet, Embraer Executive Jets',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise at FL450 reduces burn to ~122 gph. | 524 gal (3,511 lbs Jet-A). | Best-selling light jet globally for multiple years. | Single-pilot certified. | The 300E variant features increased range and Mach 0.80 max speed. | Real-world operators report 140–155 gph.',
  },
  {
    make: 'Honda',
    model: 'HondaJet Elite II',
    variant: 'HA-420 Elite II',
    yearStart: 2023,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) GE Honda HF120, 2,050 lb thrust each (over-the-wing mounted)',
    maxFuelGal: 232,
    cruiseSpeedKts: 422,
    typicalBurnGph: 110.0,
    burnRangeGph: [90.0, 135.0],
    maxRampWeightLbs: 10700,
    maxZeroFuelWeightLbs: 8300,
    basicOperatingWeightLbs: 7002,
    maxPayloadLbs: 1298,
    reservesTypicalGal: 82.5,
    reservesNbaaGal: 55.0,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Honda Aircraft HondaJet Elite II Specification Sheet, Honda Aircraft Company',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Economy cruise reduces burn to ~92 gph. | 232 gal (1,554 lbs Jet-A). | Unique over-the-wing engine mount reduces cabin noise and drag. | Single-pilot certified. | Natural laminar flow wing and composite fuselage. | Limited fuel capacity constrains range with full payload.',
  },
  {
    make: 'Pilatus',
    model: 'PC-24',
    variant: 'PC-24',
    yearStart: 2018,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-4A-QPM, 3,420 lb thrust each',
    maxFuelGal: 586,
    cruiseSpeedKts: 440,
    typicalBurnGph: 175.0,
    burnRangeGph: [145.0, 215.0],
    maxRampWeightLbs: 18300,
    maxZeroFuelWeightLbs: 13550,
    basicOperatingWeightLbs: 11640,
    maxPayloadLbs: 1910,
    reservesTypicalGal: 131.3,
    reservesNbaaGal: 87.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Pilatus PC-24 Specification Sheet, Pilatus Aircraft Ltd',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL400. Long range cruise reduces burn to ~148 gph. | 586 gal (3,926 lbs Jet-A). | Large cargo door inherited from PC-12 design; only light jet approved for unpaved runways. | Single-pilot certified. | Versatile cabin can be quickly reconfigured between passenger, cargo, and medevac layouts.',
  },
  {
    make: 'Eclipse',
    model: '550',
    variant: '550',
    yearStart: 2013,
    yearEnd: 2018,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW610F, 900 lb thrust each',
    maxFuelGal: 232,
    cruiseSpeedKts: 375,
    typicalBurnGph: 73.0,
    burnRangeGph: [60.0, 90.0],
    maxRampWeightLbs: 6034,
    maxZeroFuelWeightLbs: 4700,
    basicOperatingWeightLbs: 3710,
    maxPayloadLbs: 990,
    reservesTypicalGal: 54.8,
    reservesNbaaGal: 36.5,
    burnPenaltyPerHrPct: 3.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Eclipse 550 Specification Sheet, Eclipse Aerospace / One Aviation',
    dataSourceDate: '2016',
    operatorNotes: 'Burn at high-speed cruise, FL370. Among the most fuel-efficient jets ever produced at 73 gph. | 232 gal (1,554 lbs Jet-A). | Very light jet (VLJ) category. | Single-pilot certified. | One Aviation went bankrupt in 2018; parts and support availability is a consideration. | Small cabin limits payload; verify weight and balance carefully.',
  },
  {
    make: 'Learjet',
    model: '31A',
    variant: '31A',
    yearStart: 1991,
    yearEnd: 2003,
    fuelType: 'JetA',
    engines: '(2) Honeywell TFE731-2-3B, 3,500 lb thrust each',
    maxFuelGal: 444,
    cruiseSpeedKts: 460,
    typicalBurnGph: 175.0,
    burnRangeGph: [148.0, 215.0],
    maxRampWeightLbs: 17000,
    maxZeroFuelWeightLbs: 12500,
    basicOperatingWeightLbs: 10538,
    maxPayloadLbs: 1962,
    reservesTypicalGal: 131.3,
    reservesNbaaGal: 87.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Learjet 31A Performance Manual, Bombardier Aerospace',
    dataSourceDate: '2002',
    operatorNotes: 'Burn at high-speed cruise, FL410. The 31A is fast but thirsty for its size. | 444 gal (2,975 lbs Jet-A). | Out of production since 2003; aging fleet with increasing maintenance costs. | Tight cabin with limited headroom. | Known for excellent climb and speed performance. | Delta fins distinguish it from earlier Learjet models.',
  },
  {
    make: 'Learjet',
    model: '40XR',
    variant: '40XR',
    yearStart: 2004,
    yearEnd: 2013,
    fuelType: 'JetA',
    engines: '(2) Honeywell TFE731-20AR, 3,500 lb thrust each',
    maxFuelGal: 561,
    cruiseSpeedKts: 465,
    typicalBurnGph: 188.0,
    burnRangeGph: [158.0, 230.0],
    maxRampWeightLbs: 21000,
    maxZeroFuelWeightLbs: 15500,
    basicOperatingWeightLbs: 13055,
    maxPayloadLbs: 2445,
    reservesTypicalGal: 141.0,
    reservesNbaaGal: 94.0,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Learjet 40XR Performance Specifications, Bombardier Aerospace',
    dataSourceDate: '2012',
    operatorNotes: 'Burn at high-speed cruise, FL410. The XR (eXtended Range) variant added thrust and fuel over the base Learjet 40. | 561 gal (3,759 lbs Jet-A). | Flat floor cabin was an improvement over earlier Learjets. | Out of production; replaced by the Learjet 75. | Real-world operators report 180–200 gph.',
  },
  {
    make: 'Learjet',
    model: '45XR',
    variant: '45XR',
    yearStart: 2004,
    yearEnd: 2013,
    fuelType: 'JetA',
    engines: '(2) Honeywell TFE731-20BR, 3,500 lb thrust each',
    maxFuelGal: 638,
    cruiseSpeedKts: 465,
    typicalBurnGph: 193.0,
    burnRangeGph: [162.0, 238.0],
    maxRampWeightLbs: 21500,
    maxZeroFuelWeightLbs: 15800,
    basicOperatingWeightLbs: 13310,
    maxPayloadLbs: 2490,
    reservesTypicalGal: 144.8,
    reservesNbaaGal: 96.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Learjet 45XR Performance Specifications, Bombardier Aerospace',
    dataSourceDate: '2012',
    operatorNotes: 'Burn at high-speed cruise, FL410. Stretched cabin over the Learjet 40XR with more fuel capacity. | 638 gal (4,275 lbs Jet-A). | 8-seat cabin with full stand-up headroom. | Out of production; evolved into the Learjet 75. | Popular on the charter market.',
  },
  {
    make: 'Learjet',
    model: '60XR',
    variant: '60XR',
    yearStart: 2007,
    yearEnd: 2013,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW305A, 4,600 lb thrust each',
    maxFuelGal: 671,
    cruiseSpeedKts: 457,
    typicalBurnGph: 215.0,
    burnRangeGph: [180.0, 265.0],
    maxRampWeightLbs: 23500,
    maxZeroFuelWeightLbs: 17200,
    basicOperatingWeightLbs: 14602,
    maxPayloadLbs: 2598,
    reservesTypicalGal: 161.3,
    reservesNbaaGal: 107.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Learjet 60XR Performance Specifications, Bombardier Aerospace',
    dataSourceDate: '2012',
    operatorNotes: 'Burn at high-speed cruise, FL410. The 60XR is the largest cabin Learjet with PW305A engines. | 671 gal (4,496 lbs Jet-A). | Stand-up cabin with enclosed lavatory. | Bridges the gap between light and midsize jets. | Out of production since 2013. | Known for strong climb performance to FL510.',
  },
  {
    make: 'Learjet',
    model: '75 Liberty',
    variant: '75 Liberty',
    yearStart: 2020,
    yearEnd: 2022,
    fuelType: 'JetA',
    engines: '(2) Honeywell TFE731-40BR, 3,850 lb thrust each',
    maxFuelGal: 638,
    cruiseSpeedKts: 465,
    typicalBurnGph: 193.0,
    burnRangeGph: [162.0, 238.0],
    maxRampWeightLbs: 21500,
    maxZeroFuelWeightLbs: 15800,
    basicOperatingWeightLbs: 13380,
    maxPayloadLbs: 2420,
    reservesTypicalGal: 144.8,
    reservesNbaaGal: 96.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Learjet 75 Liberty Specification Sheet, Bombardier Aerospace',
    dataSourceDate: '2021',
    operatorNotes: 'Burn at high-speed cruise, FL410. The last Learjet produced — Bombardier ended Learjet production in 2022. | 638 gal (4,275 lbs Jet-A). | 6-seat executive configuration (down from 9 in standard 75). | Garmin G5000 avionics. | Based on the 45XR airframe with updated engines and avionics.',
  },

  // ─────────────────────────────────────────────────
  // MIDSIZE JETS
  // ─────────────────────────────────────────────────
  {
    make: 'Cessna',
    model: 'Citation XLS+',
    variant: '560XLS+',
    yearStart: 2008,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW545C, 4,119 lb thrust each',
    maxFuelGal: 550,
    cruiseSpeedKts: 441,
    typicalBurnGph: 168.0,
    burnRangeGph: [140.0, 208.0],
    maxRampWeightLbs: 20200,
    maxZeroFuelWeightLbs: 15100,
    basicOperatingWeightLbs: 12710,
    maxPayloadLbs: 2390,
    reservesTypicalGal: 126.0,
    reservesNbaaGal: 84.0,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation XLS+ Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL410. Long range cruise reduces burn to ~142 gph. | 550 gal (3,685 lbs Jet-A). | One of the best-selling midsize Citations; large installed fleet. | Stand-up cabin with enclosed lavatory. | Real-world operators commonly plan 160–175 gph. | Excellent short-field performance for a midsize jet.',
  },
  {
    make: 'Cessna',
    model: 'Citation Latitude',
    variant: '680A',
    yearStart: 2015,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW306D1, 5,907 lb thrust each',
    maxFuelGal: 743,
    cruiseSpeedKts: 446,
    typicalBurnGph: 195.0,
    burnRangeGph: [165.0, 240.0],
    maxRampWeightLbs: 30800,
    maxZeroFuelWeightLbs: 22500,
    basicOperatingWeightLbs: 18850,
    maxPayloadLbs: 3650,
    reservesTypicalGal: 146.3,
    reservesNbaaGal: 97.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation Latitude Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~168 gph. | 743 gal (4,978 lbs Jet-A). | Flat-floor, stand-up cabin; one of the most popular midsize jets in production. | Garmin G5000 avionics. | Real-world operators report 185–205 gph. | Excellent range/payload balance.',
  },
  {
    make: 'Cessna',
    model: 'Citation Longitude',
    variant: '700',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Honeywell HTF7700L, 7,665 lb thrust each',
    maxFuelGal: 1050,
    cruiseSpeedKts: 476,
    typicalBurnGph: 217.0,
    burnRangeGph: [185.0, 268.0],
    maxRampWeightLbs: 39500,
    maxZeroFuelWeightLbs: 28000,
    basicOperatingWeightLbs: 24500,
    maxPayloadLbs: 3500,
    reservesTypicalGal: 162.8,
    reservesNbaaGal: 108.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation Longitude Specification Sheet, Textron Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~188 gph. | 1,050 gal (7,035 lbs Jet-A). | Super-midsize class performance in the Citation lineup. | Flat-floor cabin with the quietest cabin in its class. | Garmin G5000 avionics. | Real-world operators report 210–230 gph.',
  },
  {
    make: 'Beechcraft',
    model: 'Premier IA',
    variant: '390',
    yearStart: 2006,
    yearEnd: 2013,
    fuelType: 'JetA',
    engines: '(2) Williams International FJ44-2A, 2,300 lb thrust each',
    maxFuelGal: 390,
    cruiseSpeedKts: 451,
    typicalBurnGph: 133.0,
    burnRangeGph: [110.0, 165.0],
    maxRampWeightLbs: 12500,
    maxZeroFuelWeightLbs: 9600,
    basicOperatingWeightLbs: 8030,
    maxPayloadLbs: 1570,
    reservesTypicalGal: 99.8,
    reservesNbaaGal: 66.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Hawker Beechcraft Premier IA Specification Sheet, Hawker Beechcraft Corporation',
    dataSourceDate: '2012',
    operatorNotes: 'Burn at high-speed cruise, FL410. Composite fuselage makes it lighter than comparable metal-construction jets. | 390 gal (2,613 lbs Jet-A). | Single-pilot certified. | Out of production since 2013 (Hawker Beechcraft bankruptcy). | Known for the widest cabin in its class at the time. | T-tail configuration.',
  },
  {
    make: 'Hawker',
    model: '400XP',
    variant: '400XP',
    yearStart: 2003,
    yearEnd: 2010,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada JT15D-5R, 2,965 lb thrust each',
    maxFuelGal: 468,
    cruiseSpeedKts: 450,
    typicalBurnGph: 165.0,
    burnRangeGph: [138.0, 203.0],
    maxRampWeightLbs: 16300,
    maxZeroFuelWeightLbs: 12200,
    basicOperatingWeightLbs: 10370,
    maxPayloadLbs: 1830,
    reservesTypicalGal: 123.8,
    reservesNbaaGal: 82.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Hawker 400XP Specification Sheet, Hawker Beechcraft Corporation',
    dataSourceDate: '2009',
    operatorNotes: 'Burn at high-speed cruise, FL410. Originally the Beechjet 400A, rebranded as Hawker 400XP. | 468 gal (3,136 lbs Jet-A). | Widely used for charter and corporate operations. | Out of production; large fleet still active. | JT15D engines are mature and well-supported. | Real-world operators report 155–175 gph.',
  },
  {
    make: 'Hawker',
    model: '800XP',
    variant: '800XP',
    yearStart: 1995,
    yearEnd: 2009,
    fuelType: 'JetA',
    engines: '(2) Honeywell TFE731-5BR, 4,660 lb thrust each',
    maxFuelGal: 786,
    cruiseSpeedKts: 447,
    typicalBurnGph: 220.0,
    burnRangeGph: [185.0, 272.0],
    maxRampWeightLbs: 28000,
    maxZeroFuelWeightLbs: 20500,
    basicOperatingWeightLbs: 16100,
    maxPayloadLbs: 4400,
    reservesTypicalGal: 165.0,
    reservesNbaaGal: 110.0,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Hawker 800XP Performance Manual, Raytheon/Hawker Beechcraft',
    dataSourceDate: '2008',
    operatorNotes: 'Burn at high-speed cruise, FL390. The 800XP was the definitive Hawker midsize with over 350 delivered. | 786 gal (5,266 lbs Jet-A). | Stand-up cabin with enclosed lavatory and full galley. | Out of production; evolved into the 850XP and 900XP. | Real-world operators report 210–235 gph. | Ventral fuel tank option increases capacity.',
  },
  {
    make: 'Embraer',
    model: 'Praetor 500',
    variant: 'EMB-545 Praetor 500',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Honeywell HTF7500E, 6,540 lb thrust each',
    maxFuelGal: 910,
    cruiseSpeedKts: 466,
    typicalBurnGph: 225.0,
    burnRangeGph: [190.0, 278.0],
    maxRampWeightLbs: 35274,
    maxZeroFuelWeightLbs: 25300,
    basicOperatingWeightLbs: 22050,
    maxPayloadLbs: 3250,
    reservesTypicalGal: 168.8,
    reservesNbaaGal: 112.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Embraer Praetor 500 Specification Sheet, Embraer Executive Jets',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~195 gph. | 910 gal (6,097 lbs Jet-A). | Evolved from the Legacy 450 with increased range. | Flat-floor, stand-up cabin. | Fly-by-wire flight controls — unique in the midsize category. | 3,340 nm NBAA IFR range makes it competitive with super-midsize jets.',
  },
  {
    make: 'Embraer',
    model: 'Praetor 600',
    variant: 'EMB-550 Praetor 600',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Honeywell HTF7500E, 7,528 lb thrust each',
    maxFuelGal: 1160,
    cruiseSpeedKts: 466,
    typicalBurnGph: 260.0,
    burnRangeGph: [220.0, 320.0],
    maxRampWeightLbs: 45415,
    maxZeroFuelWeightLbs: 32500,
    basicOperatingWeightLbs: 27800,
    maxPayloadLbs: 4700,
    reservesTypicalGal: 195.0,
    reservesNbaaGal: 130.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Embraer Praetor 600 Specification Sheet, Embraer Executive Jets',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~225 gph. | 1,160 gal (7,772 lbs Jet-A). | Evolved from the Legacy 500; super-midsize category. | Fly-by-wire flight controls. | Flat-floor cabin with full galley and enclosed lavatory. | 4,018 nm NBAA IFR range competes with large cabin jets.',
  },

  // ─────────────────────────────────────────────────
  // SUPER MIDSIZE JETS
  // ─────────────────────────────────────────────────
  {
    make: 'Bombardier',
    model: 'Challenger 350',
    variant: 'CL-30 Challenger 350',
    yearStart: 2014,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Honeywell HTF7350, 7,323 lb thrust each',
    maxFuelGal: 1231,
    cruiseSpeedKts: 470,
    typicalBurnGph: 265.0,
    burnRangeGph: [225.0, 328.0],
    maxRampWeightLbs: 40600,
    maxZeroFuelWeightLbs: 28400,
    basicOperatingWeightLbs: 24400,
    maxPayloadLbs: 4000,
    reservesTypicalGal: 198.8,
    reservesNbaaGal: 132.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Bombardier Challenger 350 Specification Sheet, Bombardier Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~230 gph. | 1,231 gal (8,248 lbs Jet-A). | Best-selling super-midsize jet globally. | Wide-body cabin with flat floor and stand-up headroom. | 3,200 nm NBAA IFR range. | Real-world operators report 255–280 gph. | Evolved from the Challenger 300.',
  },
  {
    make: 'Cessna',
    model: 'Citation Sovereign+',
    variant: '680',
    yearStart: 2013,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW306D, 5,907 lb thrust each',
    maxFuelGal: 870,
    cruiseSpeedKts: 458,
    typicalBurnGph: 215.0,
    burnRangeGph: [182.0, 265.0],
    maxRampWeightLbs: 30775,
    maxZeroFuelWeightLbs: 22200,
    basicOperatingWeightLbs: 18560,
    maxPayloadLbs: 3640,
    reservesTypicalGal: 161.3,
    reservesNbaaGal: 107.5,
    burnPenaltyPerHrPct: 3.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Cessna Citation Sovereign+ Specification Sheet, Textron Aviation',
    dataSourceDate: '2022',
    operatorNotes: 'Burn at high-speed cruise, FL430. Long range cruise reduces burn to ~185 gph. | 870 gal (5,829 lbs Jet-A). | The Sovereign+ added winglets and more powerful engines over the original Sovereign. | Flat-floor cabin for 8–12 passengers. | 3,000 nm range. | Real-world operators report 205–225 gph.',
  },
  {
    make: 'Dassault',
    model: 'Falcon 2000LXS',
    variant: '2000LXS',
    yearStart: 2014,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW308C, 7,000 lb thrust each',
    maxFuelGal: 1203,
    cruiseSpeedKts: 481,
    typicalBurnGph: 252.0,
    burnRangeGph: [213.0, 312.0],
    maxRampWeightLbs: 41000,
    maxZeroFuelWeightLbs: 29800,
    basicOperatingWeightLbs: 24800,
    maxPayloadLbs: 5000,
    reservesTypicalGal: 189.0,
    reservesNbaaGal: 126.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Dassault Falcon 2000LXS Specification Sheet, Dassault Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at high-speed cruise, FL410. Long range cruise reduces burn to ~218 gph. | 1,203 gal (8,060 lbs Jet-A). | The LXS combines the short-field performance of the 2000S with the range of the 2000LX. | Wide-body cabin with flat floor. | 4,000 nm range. | Known for excellent approach speed and short-field capability for its size.',
  },

  // ─────────────────────────────────────────────────
  // LARGE CABIN JETS
  // ─────────────────────────────────────────────────
  {
    make: 'Gulfstream',
    model: 'G450',
    variant: 'GIV-X G450',
    yearStart: 2004,
    yearEnd: 2018,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce Tay 611-8C, 13,850 lb thrust each',
    maxFuelGal: 2031,
    cruiseSpeedKts: 476,
    typicalBurnGph: 305.0,
    burnRangeGph: [258.0, 378.0],
    maxRampWeightLbs: 73900,
    maxZeroFuelWeightLbs: 48500,
    basicOperatingWeightLbs: 43200,
    maxPayloadLbs: 5300,
    reservesTypicalGal: 228.8,
    reservesNbaaGal: 152.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G450 Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2017',
    operatorNotes: 'Burn at long range cruise, FL410. High-speed cruise increases burn to ~340 gph. | 2,031 gal (13,608 lbs Jet-A). | Replaced the GIV-SP; predecessor to the G500. | Large cabin with three living zones. | 4,350 nm NBAA IFR range. | Out of production since 2018 but large fleet remains. | Real-world operators report 290–320 gph.',
  },
  {
    make: 'Gulfstream',
    model: 'G500',
    variant: 'G500',
    yearStart: 2018,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW814GA, 15,144 lb thrust each',
    maxFuelGal: 2442,
    cruiseSpeedKts: 488,
    typicalBurnGph: 300.0,
    burnRangeGph: [255.0, 372.0],
    maxRampWeightLbs: 79600,
    maxZeroFuelWeightLbs: 52000,
    basicOperatingWeightLbs: 47500,
    maxPayloadLbs: 4500,
    reservesTypicalGal: 225.0,
    reservesNbaaGal: 150.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G500 Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. High-speed cruise (Mach 0.90) increases burn to ~345 gph. | 2,442 gal (16,361 lbs Jet-A). | Fly-by-wire flight controls — first Gulfstream with active sidestick. | Symmetry Flight Deck with touchscreen avionics. | 5,200 nm range at Mach 0.85. | Real-world operators report 290–315 gph.',
  },
  {
    make: 'Gulfstream',
    model: 'G550',
    variant: 'GV-SP G550',
    yearStart: 2003,
    yearEnd: 2021,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce BR710A1-10, 15,385 lb thrust each',
    maxFuelGal: 2582,
    cruiseSpeedKts: 488,
    typicalBurnGph: 320.0,
    burnRangeGph: [272.0, 396.0],
    maxRampWeightLbs: 91400,
    maxZeroFuelWeightLbs: 58500,
    basicOperatingWeightLbs: 52600,
    maxPayloadLbs: 5900,
    reservesTypicalGal: 240.0,
    reservesNbaaGal: 160.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G550 Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2020',
    operatorNotes: 'Burn at long range cruise, FL410. High-speed cruise increases burn to ~355 gph. | 2,582 gal (17,300 lbs Jet-A). | One of the most popular large-cabin jets ever produced (~600 delivered). | 6,750 nm range at Mach 0.80. | Replaced by the G600. | Large cabin with up to four living zones. | Real-world operators report 305–340 gph.',
  },
  {
    make: 'Gulfstream',
    model: 'G600',
    variant: 'G600',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Pratt & Whitney Canada PW815GA, 15,680 lb thrust each',
    maxFuelGal: 2442,
    cruiseSpeedKts: 488,
    typicalBurnGph: 310.0,
    burnRangeGph: [263.0, 384.0],
    maxRampWeightLbs: 80600,
    maxZeroFuelWeightLbs: 53000,
    basicOperatingWeightLbs: 48450,
    maxPayloadLbs: 4550,
    reservesTypicalGal: 232.5,
    reservesNbaaGal: 155.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G600 Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. High-speed cruise (Mach 0.90) increases burn to ~350 gph. | 2,442 gal (16,361 lbs Jet-A). | Successor to the G550; fly-by-wire with active sidestick. | Symmetry Flight Deck. | 6,500 nm range at Mach 0.85. | Shares wing and engine commonality with the G500. | Real-world operators report 300–325 gph.',
  },
  {
    make: 'Gulfstream',
    model: 'G650ER',
    variant: 'G650ER',
    yearStart: 2014,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce BR725A1-12, 16,100 lb thrust each',
    maxFuelGal: 2950,
    cruiseSpeedKts: 516,
    typicalBurnGph: 340.0,
    burnRangeGph: [289.0, 420.0],
    maxRampWeightLbs: 99600,
    maxZeroFuelWeightLbs: 64000,
    basicOperatingWeightLbs: 55800,
    maxPayloadLbs: 8200,
    reservesTypicalGal: 255.0,
    reservesNbaaGal: 170.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G650ER Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. High-speed cruise (Mach 0.90) increases burn to ~385 gph. | 2,950 gal (19,765 lbs Jet-A). | 7,500 nm range at Mach 0.85 — one of the longest-range business jets. | Mach 0.925 max operating speed. | Wide cabin with up to four living zones. | Real-world operators report 330–360 gph.',
  },
  {
    make: 'Gulfstream',
    model: 'G700',
    variant: 'G700',
    yearStart: 2022,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce Pearl 700, 18,250 lb thrust each',
    maxFuelGal: 3177,
    cruiseSpeedKts: 516,
    typicalBurnGph: 350.0,
    burnRangeGph: [298.0, 434.0],
    maxRampWeightLbs: 107600,
    maxZeroFuelWeightLbs: 69000,
    basicOperatingWeightLbs: 60300,
    maxPayloadLbs: 8700,
    reservesTypicalGal: 262.5,
    reservesNbaaGal: 175.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Gulfstream G700 Specification Sheet, Gulfstream Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. High-speed cruise (Mach 0.90) increases burn to ~395 gph. | 3,177 gal (21,286 lbs Jet-A). | Largest-cabin purpose-built business jet. | 7,750 nm range at Mach 0.85. | Five living zones in standard configuration. | Fly-by-wire with Symmetry Flight Deck. | Rolls-Royce Pearl 700 engines are purpose-built for this aircraft.',
  },
  {
    make: 'Bombardier',
    model: 'Global 5500',
    variant: 'BD-700-1A11 Global 5500',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce Pearl 15, 15,125 lb thrust each',
    maxFuelGal: 1910,
    cruiseSpeedKts: 488,
    typicalBurnGph: 295.0,
    burnRangeGph: [250.0, 365.0],
    maxRampWeightLbs: 92500,
    maxZeroFuelWeightLbs: 58000,
    basicOperatingWeightLbs: 52350,
    maxPayloadLbs: 5650,
    reservesTypicalGal: 221.3,
    reservesNbaaGal: 147.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Bombardier Global 5500 Specification Sheet, Bombardier Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. | 1,910 gal (12,797 lbs Jet-A). | Successor to the Global 5000; same airframe with new Rolls-Royce Pearl 15 engines. | 5,900 nm range. | Three-zone cabin. | Bombardier Vision flight deck with Rockwell Collins Pro Line Fusion avionics. | Real-world operators report 285–310 gph.',
  },
  {
    make: 'Bombardier',
    model: 'Global 6500',
    variant: 'BD-700-1A10 Global 6500',
    yearStart: 2019,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) Rolls-Royce Pearl 15, 15,125 lb thrust each',
    maxFuelGal: 2171,
    cruiseSpeedKts: 488,
    typicalBurnGph: 315.0,
    burnRangeGph: [267.0, 390.0],
    maxRampWeightLbs: 99500,
    maxZeroFuelWeightLbs: 62000,
    basicOperatingWeightLbs: 55800,
    maxPayloadLbs: 6200,
    reservesTypicalGal: 236.3,
    reservesNbaaGal: 157.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Bombardier Global 6500 Specification Sheet, Bombardier Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. | 2,171 gal (14,546 lbs Jet-A). | Successor to the Global 6000; Rolls-Royce Pearl 15 engines. | 6,600 nm range. | Three-zone cabin with widest cross-section in its class. | Competes directly with G550/G600. | Real-world operators report 305–330 gph.',
  },
  {
    make: 'Bombardier',
    model: 'Global 7500',
    variant: 'BD-700-2A12 Global 7500',
    yearStart: 2018,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) GE Passport, 18,920 lb thrust each',
    maxFuelGal: 2656,
    cruiseSpeedKts: 516,
    typicalBurnGph: 348.0,
    burnRangeGph: [296.0, 430.0],
    maxRampWeightLbs: 104800,
    maxZeroFuelWeightLbs: 68000,
    basicOperatingWeightLbs: 59600,
    maxPayloadLbs: 8400,
    reservesTypicalGal: 261.0,
    reservesNbaaGal: 174.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Bombardier Global 7500 Specification Sheet, Bombardier Aerospace',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL430. High-speed cruise (Mach 0.90) increases burn to ~395 gph. | 2,656 gal (17,795 lbs Jet-A). | 7,700 nm range at Mach 0.85 — longest-range Bombardier. | Four living zones with full kitchen. | GE Passport engines purpose-built for this aircraft. | Fly-by-wire. | Competes with G650ER/G700. | Real-world operators report 340–365 gph.',
  },
  {
    make: 'Dassault',
    model: 'Falcon 7X',
    variant: '7X',
    yearStart: 2007,
    yearEnd: 2019,
    fuelType: 'JetA',
    engines: '(3) Pratt & Whitney Canada PW307A, 6,402 lb thrust each',
    maxFuelGal: 1585,
    cruiseSpeedKts: 481,
    typicalBurnGph: 270.0,
    burnRangeGph: [230.0, 334.0],
    maxRampWeightLbs: 69000,
    maxZeroFuelWeightLbs: 47000,
    basicOperatingWeightLbs: 40350,
    maxPayloadLbs: 6650,
    reservesTypicalGal: 202.5,
    reservesNbaaGal: 135.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Dassault Falcon 7X Specification Sheet, Dassault Aviation',
    dataSourceDate: '2018',
    operatorNotes: 'Burn at long range cruise, FL410. Tri-jet configuration with three PW307A engines. | 1,585 gal (10,620 lbs Jet-A). | First business jet with fly-by-wire (digital flight controls). | 5,950 nm range. | Replaced by the Falcon 8X. | Three-engine configuration provides excellent hot-and-high and single-engine performance. | Real-world operators report 260–285 gph.',
  },
  {
    make: 'Dassault',
    model: 'Falcon 8X',
    variant: '8X',
    yearStart: 2016,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(3) Pratt & Whitney Canada PW307D, 6,722 lb thrust each',
    maxFuelGal: 1797,
    cruiseSpeedKts: 481,
    typicalBurnGph: 275.0,
    burnRangeGph: [234.0, 340.0],
    maxRampWeightLbs: 73000,
    maxZeroFuelWeightLbs: 49500,
    basicOperatingWeightLbs: 42200,
    maxPayloadLbs: 7300,
    reservesTypicalGal: 206.3,
    reservesNbaaGal: 137.5,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'manufacturer_spec',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Dassault Falcon 8X Specification Sheet, Dassault Aviation',
    dataSourceDate: '2023',
    operatorNotes: 'Burn at long range cruise, FL410. Tri-jet configuration with three PW307D engines. | 1,797 gal (12,040 lbs Jet-A). | Stretched and improved successor to the Falcon 7X. | 6,450 nm range. | Fly-by-wire. | More fuel-efficient per-seat-mile than twin-engine competitors due to optimized engine sizing. | Real-world operators report 265–290 gph.',
  },
  {
    make: 'Dassault',
    model: 'Falcon 900LX',
    variant: '900LX',
    yearStart: 2008,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(3) Honeywell TFE731-60, 5,000 lb thrust each',
    maxFuelGal: 1422,
    cruiseSpeedKts: 481,
    typicalBurnGph: 250.0,
    burnRangeGph: [212.0, 310.0],
    maxRampWeightLbs: 49000,
    maxZeroFuelWeightLbs: 34500,
    basicOperatingWeightLbs: 29050,
    maxPayloadLbs: 5450,
    reservesTypicalGal: 187.5,
    reservesNbaaGal: 125.0,
    burnPenaltyPerHrPct: 4.0,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Dassault Falcon 900LX Specification Sheet, Dassault Aviation',
    dataSourceDate: '2022',
    operatorNotes: 'Burn at long range cruise, FL410. Tri-jet configuration with three TFE731-60 engines. | 1,422 gal (9,527 lbs Jet-A). | The 900LX added winglets and increased range over the 900EX. | 4,750 nm range. | Three-engine reliability makes it popular for overwater and remote operations. | Real-world operators report 240–265 gph.',
  },
  {
    make: 'Embraer',
    model: 'Lineage 1000E',
    variant: 'ERJ-190-100 ECJ Lineage 1000E',
    yearStart: 2014,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) GE CF34-10E7, 18,500 lb thrust each',
    maxFuelGal: 3172,
    cruiseSpeedKts: 470,
    typicalBurnGph: 420.0,
    burnRangeGph: [355.0, 520.0],
    maxRampWeightLbs: 120152,
    maxZeroFuelWeightLbs: 82000,
    basicOperatingWeightLbs: 72300,
    maxPayloadLbs: 9700,
    reservesTypicalGal: 315.0,
    reservesNbaaGal: 210.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'manufacturer_spec',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Embraer Lineage 1000E Specification Sheet, Embraer Executive Jets',
    dataSourceDate: '2020',
    operatorNotes: 'Burn at long range cruise, FL410. Based on the Embraer 190 airliner platform. | 3,172 gal (21,252 lbs Jet-A). | Ultra-large cabin — up to five living zones with 6 ft+ headroom. | 4,600 nm range. | Very few produced; niche VVIP market. | Airliner-derived economics with lower per-hour engine costs than purpose-built large-cabin jets. | Real-world operators report 400–450 gph.',
  },
  {
    make: 'Boeing',
    model: 'BBJ (737-700 based)',
    variant: 'BBJ1',
    yearStart: 1998,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) CFM International CFM56-7B27, 27,300 lb thrust each',
    maxFuelGal: 6875,
    cruiseSpeedKts: 470,
    typicalBurnGph: 660.0,
    burnRangeGph: [560.0, 815.0],
    maxRampWeightLbs: 171000,
    maxZeroFuelWeightLbs: 115000,
    basicOperatingWeightLbs: 100000,
    maxPayloadLbs: 15000,
    reservesTypicalGal: 495.0,
    reservesNbaaGal: 330.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'community_estimate',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Boeing Business Jet BBJ1 General Specifications, Boeing Commercial Airplanes',
    dataSourceDate: '2020',
    operatorNotes: 'Burn at long range cruise, FL390. Based on the 737-700 airframe with strengthened wing and auxiliary fuel tanks. | 6,875 gal (46,063 lbs Jet-A). | 6,200 nm range with aux tanks. | Cabin configured to customer specification — typically 25–50 VVIP seats. | Operating costs are airline-level; not comparable to purpose-built business jets. | Requires crew of at least 2 pilots and typically 1-2 cabin crew. | Weight estimates are approximate as each BBJ is custom-configured.',
  },
  {
    make: 'Airbus',
    model: 'ACJ320',
    variant: 'ACJ320neo',
    yearStart: 2000,
    yearEnd: null,
    fuelType: 'JetA',
    engines: '(2) CFM International LEAP-1A26, 27,120 lb thrust each',
    maxFuelGal: 6260,
    cruiseSpeedKts: 470,
    typicalBurnGph: 700.0,
    burnRangeGph: [595.0, 865.0],
    maxRampWeightLbs: 170000,
    maxZeroFuelWeightLbs: 114000,
    basicOperatingWeightLbs: 99500,
    maxPayloadLbs: 14500,
    reservesTypicalGal: 525.0,
    reservesNbaaGal: 350.0,
    burnPenaltyPerHrPct: 4.5,
    confidence: {
      weights: 'community_estimate',
      fuelCapacity: 'manufacturer_spec',
      burnRate: 'community_estimate',
      burnPenalty: 'community_estimate',
      reserves: 'community_estimate',
    },
    dataSource: 'Airbus ACJ320neo General Specifications, Airbus Corporate Jets',
    dataSourceDate: '2022',
    operatorNotes: 'Burn at long range cruise, FL390. Based on the A320neo airframe with additional center fuel tanks. | 6,260 gal (41,942 lbs Jet-A). | 6,000 nm range with ACTs. | Neo variant features LEAP-1A engines with significant fuel savings over CEO. | Widest cabin in the narrowbody airliner-based bizjet category. | Typically configured for 25–50 VVIP passengers. | Weight estimates are approximate as each ACJ is custom-configured.',
  },
];
